name: manual_clock
description: A package for testing current time related code.
version: 1.3.0
repository: https://github.com/sousyokunotomonokai/manual_clock
issue_tracker: https://github.com/sousyokunotomonokai/manual_clock/issues
environment:
  sdk: ^3.1.3

dependencies:
  clock: ^1.1.1
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.0.0
  mockito: ^5.4.2
  test: ^1.21.0
